/*
SQLyog Community v10.3 
MySQL - 5.7.21 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `country_artemis` (
	`artemis` varchar (768),
	`btn` varchar (768)
); 
insert into `country_artemis` (`artemis`, `btn`) values('Afghanistan','AFGHANISTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Aland Islands','ALAND ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Albania','ALBANIA');
insert into `country_artemis` (`artemis`, `btn`) values('Algeria','ALGERIA');
insert into `country_artemis` (`artemis`, `btn`) values('American Samoa','AMERICAN SAMOA');
insert into `country_artemis` (`artemis`, `btn`) values('Andorra','ANDORRA');
insert into `country_artemis` (`artemis`, `btn`) values('Angola','ANGOLA');
insert into `country_artemis` (`artemis`, `btn`) values('Anguilla','ANGUILLA');
insert into `country_artemis` (`artemis`, `btn`) values('Antarctica','ANTARCTICA');
insert into `country_artemis` (`artemis`, `btn`) values('Antigua and Barbuda','ANTIGUA AND BARBUDA');
insert into `country_artemis` (`artemis`, `btn`) values('Argentina','ARGENTINA');
insert into `country_artemis` (`artemis`, `btn`) values('Armenia','ARMENIA');
insert into `country_artemis` (`artemis`, `btn`) values('Aruba','ARUBA');
insert into `country_artemis` (`artemis`, `btn`) values('Australia','AUSTRALIA');
insert into `country_artemis` (`artemis`, `btn`) values('Austria','AUSTRIA');
insert into `country_artemis` (`artemis`, `btn`) values('Azerbaijan','AZERBAIJAN');
insert into `country_artemis` (`artemis`, `btn`) values('Bahamas','BAHAMAS');
insert into `country_artemis` (`artemis`, `btn`) values('Bahrain','BAHRAIN');
insert into `country_artemis` (`artemis`, `btn`) values('Bangladesh','BANGLADESH');
insert into `country_artemis` (`artemis`, `btn`) values('Barbados','BARBADOS');
insert into `country_artemis` (`artemis`, `btn`) values('Belarus','BELARUS');
insert into `country_artemis` (`artemis`, `btn`) values('Belgium','BELGIUM');
insert into `country_artemis` (`artemis`, `btn`) values('Belize','BELIZE');
insert into `country_artemis` (`artemis`, `btn`) values('Benin','BENIN');
insert into `country_artemis` (`artemis`, `btn`) values('Bermuda','BERMUDA');
insert into `country_artemis` (`artemis`, `btn`) values('Bhutan','BHUTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Bolivia (Plurinational State of)','BOLIVIA');
insert into `country_artemis` (`artemis`, `btn`) values('Bonaire, Sint Eustatius and Saba','CARIBBEAN NETHERLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Bosnia and Herzegovina','BOSNIA AND HERZEGOVINA');
insert into `country_artemis` (`artemis`, `btn`) values('Botswana','BOTSWANA');
insert into `country_artemis` (`artemis`, `btn`) values('Bouvet Island','BOUVET ISLAND');
insert into `country_artemis` (`artemis`, `btn`) values('Brazil','BRAZIL');
insert into `country_artemis` (`artemis`, `btn`) values('British Indian Ocean Territory','BRITISH INDIAN OCEAN TERRITORY');
insert into `country_artemis` (`artemis`, `btn`) values('Brunei Darussalam','BRUNEI');
insert into `country_artemis` (`artemis`, `btn`) values('Bulgaria','BULGARIA');
insert into `country_artemis` (`artemis`, `btn`) values('Burkina Faso','BURKINA FASO');
insert into `country_artemis` (`artemis`, `btn`) values('Burundi','BURUNDI');
insert into `country_artemis` (`artemis`, `btn`) values('Cabo Verde','CAPE VERDE');
insert into `country_artemis` (`artemis`, `btn`) values('Cambodia','CAMBODIA');
insert into `country_artemis` (`artemis`, `btn`) values('Cameroon','CAMEROON');
insert into `country_artemis` (`artemis`, `btn`) values('Canada','CANADA');
insert into `country_artemis` (`artemis`, `btn`) values('Cayman Islands','CAYMAN ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Central African Republic','CENTRAL AFRICAN REPUBLIC');
insert into `country_artemis` (`artemis`, `btn`) values('Chad','CHAD');
insert into `country_artemis` (`artemis`, `btn`) values('Chile','CHILE');
insert into `country_artemis` (`artemis`, `btn`) values('China','CHINA');
insert into `country_artemis` (`artemis`, `btn`) values('Christmas Island','CHRISTMAS ISLAND');
insert into `country_artemis` (`artemis`, `btn`) values('Cocos (Keeling) Islands','COCOS (KEELING) ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Colombia','COLOMBIA');
insert into `country_artemis` (`artemis`, `btn`) values('Comoros','COMOROS');
insert into `country_artemis` (`artemis`, `btn`) values('Congo','CONGO (REPUBLIC OF)');
insert into `country_artemis` (`artemis`, `btn`) values('Congo (Democratic Republic of the)','DEMOCRATIC REPUBLIC OF THE CONGO');
insert into `country_artemis` (`artemis`, `btn`) values('Cook Islands','COOK ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Costa Rica','COSTA RICA');
insert into `country_artemis` (`artemis`, `btn`) values('Cote d\'Ivoire','COTE D\'IVOIRE (IVORY COAST)');
insert into `country_artemis` (`artemis`, `btn`) values('Croatia','CROATIA');
insert into `country_artemis` (`artemis`, `btn`) values('Cuba','CUBA');
insert into `country_artemis` (`artemis`, `btn`) values('Curacao','CURACAO');
insert into `country_artemis` (`artemis`, `btn`) values('Cyprus','CYPRUS');
insert into `country_artemis` (`artemis`, `btn`) values('Czechia','CZECH REPUBLIC');
insert into `country_artemis` (`artemis`, `btn`) values('Denmark','DENMARK');
insert into `country_artemis` (`artemis`, `btn`) values('Djibouti','DJIBOUTI');
insert into `country_artemis` (`artemis`, `btn`) values('Dominica','DOMINICA');
insert into `country_artemis` (`artemis`, `btn`) values('Dominican Republic','DOMINICAN REPUBLIC');
insert into `country_artemis` (`artemis`, `btn`) values('Ecuador','ECUADOR');
insert into `country_artemis` (`artemis`, `btn`) values('Egypt','EGYPT');
insert into `country_artemis` (`artemis`, `btn`) values('El Salvador','EL SALVADOR');
insert into `country_artemis` (`artemis`, `btn`) values('Equatorial Guinea','EQUATORIAL GUINEA');
insert into `country_artemis` (`artemis`, `btn`) values('Eritrea','ERITREA');
insert into `country_artemis` (`artemis`, `btn`) values('Estonia','ESTONIA');
insert into `country_artemis` (`artemis`, `btn`) values('Ethiopia','ETHIOPIA');
insert into `country_artemis` (`artemis`, `btn`) values('Falkland Islands','FALKLAND ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Faroe Islands','FAROE ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Fiji','FIJI');
insert into `country_artemis` (`artemis`, `btn`) values('Finland','FINLAND');
insert into `country_artemis` (`artemis`, `btn`) values('France','FRANCE');
insert into `country_artemis` (`artemis`, `btn`) values('French Guiana','FRENCH GUIANA');
insert into `country_artemis` (`artemis`, `btn`) values('French Polynesia','FRENCH POLYNESIA');
insert into `country_artemis` (`artemis`, `btn`) values('French Southern Territories','FRENCH SOUTHERN TERRITORIES');
insert into `country_artemis` (`artemis`, `btn`) values('Gabon','GABON');
insert into `country_artemis` (`artemis`, `btn`) values('Gambia','GAMBIA');
insert into `country_artemis` (`artemis`, `btn`) values('Georgia','GEORGIA');
insert into `country_artemis` (`artemis`, `btn`) values('Germany','GERMANY');
insert into `country_artemis` (`artemis`, `btn`) values('Ghana','GHANA');
insert into `country_artemis` (`artemis`, `btn`) values('Gibraltar','GIBRALTAR');
insert into `country_artemis` (`artemis`, `btn`) values('Greece','GREECE');
insert into `country_artemis` (`artemis`, `btn`) values('Greenland','GREENLAND');
insert into `country_artemis` (`artemis`, `btn`) values('Grenada','GRENADA');
insert into `country_artemis` (`artemis`, `btn`) values('Guadeloupe','GUADELOUPE');
insert into `country_artemis` (`artemis`, `btn`) values('Guam','GUAM');
insert into `country_artemis` (`artemis`, `btn`) values('Guatemala','GUATEMALA');
insert into `country_artemis` (`artemis`, `btn`) values('Guernsey','GUERNSEY');
insert into `country_artemis` (`artemis`, `btn`) values('Guinea','GUINEA');
insert into `country_artemis` (`artemis`, `btn`) values('Guinea-Bissau','GUINEA-BISSAU');
insert into `country_artemis` (`artemis`, `btn`) values('Guyana','GUYANA');
insert into `country_artemis` (`artemis`, `btn`) values('Haiti','HAITI');
insert into `country_artemis` (`artemis`, `btn`) values('Heard Island and McDonald Islands','HEARD AND MCDONALD ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Holy See','VATICAN');
insert into `country_artemis` (`artemis`, `btn`) values('Honduras','HONDURAS');
insert into `country_artemis` (`artemis`, `btn`) values('Hong Kong','HONG KONG');
insert into `country_artemis` (`artemis`, `btn`) values('Hungary','HUNGARY');
insert into `country_artemis` (`artemis`, `btn`) values('Iceland','ICELAND');
insert into `country_artemis` (`artemis`, `btn`) values('India','INDIA');
insert into `country_artemis` (`artemis`, `btn`) values('Indonesia','INDONESIA');
insert into `country_artemis` (`artemis`, `btn`) values('Iran (Islamic Republic of)','IRAN');
insert into `country_artemis` (`artemis`, `btn`) values('Iraq','IRAQ');
insert into `country_artemis` (`artemis`, `btn`) values('Ireland','IRELAND');
insert into `country_artemis` (`artemis`, `btn`) values('Isle of Man','ISLE OF MAN');
insert into `country_artemis` (`artemis`, `btn`) values('Israel','ISRAEL');
insert into `country_artemis` (`artemis`, `btn`) values('Italy','ITALY');
insert into `country_artemis` (`artemis`, `btn`) values('Jamaica','JAMAICA');
insert into `country_artemis` (`artemis`, `btn`) values('Japan','JAPAN');
insert into `country_artemis` (`artemis`, `btn`) values('Jersey','JERSEY');
insert into `country_artemis` (`artemis`, `btn`) values('Jordan','JORDAN');
insert into `country_artemis` (`artemis`, `btn`) values('Kazakhstan','KAZAKHSTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Kenya','KENYA');
insert into `country_artemis` (`artemis`, `btn`) values('Kiribati','KIRIBATI');
insert into `country_artemis` (`artemis`, `btn`) values('Korea (Democratic People\'s Republic of)','NORTH KOREA');
insert into `country_artemis` (`artemis`, `btn`) values('Korea (Republic of)','SOUTH KOREA');
insert into `country_artemis` (`artemis`, `btn`) values('Kuwait','KUWAIT');
insert into `country_artemis` (`artemis`, `btn`) values('Kyrgyzstan','KYRGYZSTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Lao People\'s Democratic Republic','LAOS');
insert into `country_artemis` (`artemis`, `btn`) values('Latvia','LATVIA');
insert into `country_artemis` (`artemis`, `btn`) values('Lebanon','LEBANON');
insert into `country_artemis` (`artemis`, `btn`) values('Lesotho','LESOTHO');
insert into `country_artemis` (`artemis`, `btn`) values('Liberia','LIBERIA');
insert into `country_artemis` (`artemis`, `btn`) values('Libya','LIBYA');
insert into `country_artemis` (`artemis`, `btn`) values('Liechtenstein','LIECHTENSTEIN');
insert into `country_artemis` (`artemis`, `btn`) values('Lithuania','LITHUANIA');
insert into `country_artemis` (`artemis`, `btn`) values('Luxembourg','LUXEMBOURG');
insert into `country_artemis` (`artemis`, `btn`) values('Macao','MACAU');
insert into `country_artemis` (`artemis`, `btn`) values('Macedonia (the former Yugoslav Republic of)','MACEDONIA');
insert into `country_artemis` (`artemis`, `btn`) values('Madagascar','MADAGASCAR');
insert into `country_artemis` (`artemis`, `btn`) values('Malawi','MALAWI');
insert into `country_artemis` (`artemis`, `btn`) values('Malaysia','MALAYSIA');
insert into `country_artemis` (`artemis`, `btn`) values('Maldives','MALDIVES');
insert into `country_artemis` (`artemis`, `btn`) values('Mali','MALI');
insert into `country_artemis` (`artemis`, `btn`) values('Malta','MALTA');
insert into `country_artemis` (`artemis`, `btn`) values('Marshall Islands','MARSHALL ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Martinique','MARTINIQUE');
insert into `country_artemis` (`artemis`, `btn`) values('Mauritania','MAURITANIA');
insert into `country_artemis` (`artemis`, `btn`) values('Mauritius','MAURITIUS');
insert into `country_artemis` (`artemis`, `btn`) values('Mayotte','MAYOTTE');
insert into `country_artemis` (`artemis`, `btn`) values('Mexico','MEXICO');
insert into `country_artemis` (`artemis`, `btn`) values('Micronesia (Federated States of)','MICRONESIA');
insert into `country_artemis` (`artemis`, `btn`) values('Moldova (Republic of)','MOLDOVA');
insert into `country_artemis` (`artemis`, `btn`) values('Monaco','MONACO');
insert into `country_artemis` (`artemis`, `btn`) values('Mongolia','MONGOLIA');
insert into `country_artemis` (`artemis`, `btn`) values('Montenegro','MONTENEGRO');
insert into `country_artemis` (`artemis`, `btn`) values('Montserrat','MONTSERRAT');
insert into `country_artemis` (`artemis`, `btn`) values('Morocco','MOROCCO');
insert into `country_artemis` (`artemis`, `btn`) values('Mozambique','MOZAMBIQUE');
insert into `country_artemis` (`artemis`, `btn`) values('Myanmar','BURMA (REPUBLIC OF THE UNION OF MYANMAR)');
insert into `country_artemis` (`artemis`, `btn`) values('Namibia','NAMIBIA');
insert into `country_artemis` (`artemis`, `btn`) values('Nauru','NAURU');
insert into `country_artemis` (`artemis`, `btn`) values('Nepal','NEPAL');
insert into `country_artemis` (`artemis`, `btn`) values('Netherlands','NETHERLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('New Caledonia','NEW CALEDONIA');
insert into `country_artemis` (`artemis`, `btn`) values('New Zealand','NEW ZEALAND');
insert into `country_artemis` (`artemis`, `btn`) values('Nicaragua','NICARAGUA');
insert into `country_artemis` (`artemis`, `btn`) values('Niger','NIGER');
insert into `country_artemis` (`artemis`, `btn`) values('Nigeria','NIGERIA');
insert into `country_artemis` (`artemis`, `btn`) values('Niue','NIUE');
insert into `country_artemis` (`artemis`, `btn`) values('Norfolk Island','NORFOLK ISLAND');
insert into `country_artemis` (`artemis`, `btn`) values('Northern Mariana Islands','NORTHERN MARIANA ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Norway','NORWAY');
insert into `country_artemis` (`artemis`, `btn`) values('Oman','OMAN');
insert into `country_artemis` (`artemis`, `btn`) values('Pakistan','PAKISTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Palau','PALAU');
insert into `country_artemis` (`artemis`, `btn`) values('Palestine, State of','PALESTINE');
insert into `country_artemis` (`artemis`, `btn`) values('Panama','PANAMA');
insert into `country_artemis` (`artemis`, `btn`) values('Papua New Guinea','PAPUA NEW GUINEA');
insert into `country_artemis` (`artemis`, `btn`) values('Paraguay','PARAGUAY');
insert into `country_artemis` (`artemis`, `btn`) values('Peru','PERU');
insert into `country_artemis` (`artemis`, `btn`) values('Philippines','PHILIPPINES');
insert into `country_artemis` (`artemis`, `btn`) values('Pitcairn','PITCAIRN ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Poland','POLAND');
insert into `country_artemis` (`artemis`, `btn`) values('Portugal','PORTUGAL');
insert into `country_artemis` (`artemis`, `btn`) values('Puerto Rico','PUERTO RICO');
insert into `country_artemis` (`artemis`, `btn`) values('Qatar','QATAR');
insert into `country_artemis` (`artemis`, `btn`) values('Reunion','REUNION');
insert into `country_artemis` (`artemis`, `btn`) values('Romania','ROMANIA');
insert into `country_artemis` (`artemis`, `btn`) values('Russian Federation','RUSSIAN FEDERATION');
insert into `country_artemis` (`artemis`, `btn`) values('Rwanda','RWANDA');
insert into `country_artemis` (`artemis`, `btn`) values('Saint Barthelemy','SAINT BARTHELEMY');
insert into `country_artemis` (`artemis`, `btn`) values('Saint Helena, Ascension and Tristan da Cunha','SAINT HELENA');
insert into `country_artemis` (`artemis`, `btn`) values('Saint Kitts and Nevis','SAINT KITTS AND NEVIS');
insert into `country_artemis` (`artemis`, `btn`) values('Saint Lucia','SAINT LUCIA');
insert into `country_artemis` (`artemis`, `btn`) values('Saint Martin (French part)','SAINT MARTIN (FRANCE)');
insert into `country_artemis` (`artemis`, `btn`) values('Saint Pierre and Miquelon','SAINT PIERRE AND MIQUELON');
insert into `country_artemis` (`artemis`, `btn`) values('Saint Vincent and the Grenadines','SAINT VINCENT AND GRENADINES');
insert into `country_artemis` (`artemis`, `btn`) values('Samoa','SAMOA');
insert into `country_artemis` (`artemis`, `btn`) values('San Marino','SAN MARINO');
insert into `country_artemis` (`artemis`, `btn`) values('Sao Tome and Principe','SAO TOME AND PRINCIPE');
insert into `country_artemis` (`artemis`, `btn`) values('Saudi Arabia','SAUDI ARABIA');
insert into `country_artemis` (`artemis`, `btn`) values('Senegal','SENEGAL');
insert into `country_artemis` (`artemis`, `btn`) values('Serbia','SERBIA');
insert into `country_artemis` (`artemis`, `btn`) values('Seychelles','SEYCHELLES');
insert into `country_artemis` (`artemis`, `btn`) values('Sierra Leone','SIERRA LEONE');
insert into `country_artemis` (`artemis`, `btn`) values('Singapore','SINGAPORE');
insert into `country_artemis` (`artemis`, `btn`) values('Sint Maarten (Dutch part)','SAINT MARTIN (NETHERLANDS)');
insert into `country_artemis` (`artemis`, `btn`) values('Slovakia','SLOVAKIA');
insert into `country_artemis` (`artemis`, `btn`) values('Slovenia','SLOVENIA');
insert into `country_artemis` (`artemis`, `btn`) values('Solomon Islands','SOLOMON ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Somalia','SOMALIA');
insert into `country_artemis` (`artemis`, `btn`) values('South Africa','SOUTH AFRICA');
insert into `country_artemis` (`artemis`, `btn`) values('South Georgia and the South Sandwich Islands','SOUTH GEORGIA & SOUTH SANDWICH ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('South Sudan','SOUTH SUDAN');
insert into `country_artemis` (`artemis`, `btn`) values('Spain','SPAIN');
insert into `country_artemis` (`artemis`, `btn`) values('Sri Lanka','SRI LANKA');
insert into `country_artemis` (`artemis`, `btn`) values('Sudan','SUDAN');
insert into `country_artemis` (`artemis`, `btn`) values('Suriname','SURINAME');
insert into `country_artemis` (`artemis`, `btn`) values('Svalbard and Jan Mayen','SVALBARD AND JAN MAYEN ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Swaziland','SWAZILAND');
insert into `country_artemis` (`artemis`, `btn`) values('Sweden','SWEDEN');
insert into `country_artemis` (`artemis`, `btn`) values('Switzerland','SWITZERLAND');
insert into `country_artemis` (`artemis`, `btn`) values('Syrian Arab Republic','SYRIA');
insert into `country_artemis` (`artemis`, `btn`) values('Taiwan','TAIWAN');
insert into `country_artemis` (`artemis`, `btn`) values('Tajikistan','TAJIKISTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Tanzania, United Republic of','TANZANIA');
insert into `country_artemis` (`artemis`, `btn`) values('Thailand','THAILAND');
insert into `country_artemis` (`artemis`, `btn`) values('Timor-Leste','TIMOR-LESTE');
insert into `country_artemis` (`artemis`, `btn`) values('Togo','TOGO');
insert into `country_artemis` (`artemis`, `btn`) values('Tokelau','TOKELAU');
insert into `country_artemis` (`artemis`, `btn`) values('Tonga','TONGA');
insert into `country_artemis` (`artemis`, `btn`) values('Trinidad and Tobago','TRINIDAD AND TOBAGO');
insert into `country_artemis` (`artemis`, `btn`) values('Tunisia','TUNISIA');
insert into `country_artemis` (`artemis`, `btn`) values('Turkey','TURKEY');
insert into `country_artemis` (`artemis`, `btn`) values('Turkmenistan','TURKMENISTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Turks and Caicos Islands','TURKS AND CAICOS ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Tuvalu','TUVALU');
insert into `country_artemis` (`artemis`, `btn`) values('Uganda','UGANDA');
insert into `country_artemis` (`artemis`, `btn`) values('Ukraine','UKRAINE');
insert into `country_artemis` (`artemis`, `btn`) values('United Arab Emirates','UNITED ARAB EMIRATES');
insert into `country_artemis` (`artemis`, `btn`) values('United Kingdom of Great Britain and Northern Ireland','UNITED KINGDOM');
insert into `country_artemis` (`artemis`, `btn`) values('United States Minor Outlying Islands','UNITED STATES MINOR OUTLYING ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('United States of America','UNITED STATES OF AMERICA');
insert into `country_artemis` (`artemis`, `btn`) values('Uruguay','URUGUAY');
insert into `country_artemis` (`artemis`, `btn`) values('Uzbekistan','UZBEKISTAN');
insert into `country_artemis` (`artemis`, `btn`) values('Vanuatu','VANUATU');
insert into `country_artemis` (`artemis`, `btn`) values('Venezuela (Bolivarian Republic of)','VENEZUELA');
insert into `country_artemis` (`artemis`, `btn`) values('Vietnam','VIETNAM');
insert into `country_artemis` (`artemis`, `btn`) values('Virgin Islands (British)','BRITISH VIRGIN ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Virgin Islands (U.S.)','UNITED STATES VIRGIN ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Wallis and Futuna','WALLIS AND FUTUNA ISLANDS');
insert into `country_artemis` (`artemis`, `btn`) values('Western Sahara','WESTERN SAHARAN');
insert into `country_artemis` (`artemis`, `btn`) values('Yemen','YEMEN');
insert into `country_artemis` (`artemis`, `btn`) values('Zambia','ZAMBIA');
insert into `country_artemis` (`artemis`, `btn`) values('Zimbabwe','ZIMBABWE');
