/*
SQLyog Community v10.3 
MySQL - 5.7.21 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `nationality` (
	`id` int (11),
	`name` varchar (765),
	`rating` smallint (4),
	`is_sanctioned` tinyint (1),
	`is_active` tinyint (4),
	`datetime_created` datetime ,
	`datetime_updated` datetime 
); 
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('1','ABKHAZIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('2','AFGHANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('3','ALANDIC',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('4','ALBANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('5','ALGERIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('6','U.S. TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('7','ANDORRAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('8','ANGOLAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('9','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('10','ANTARCTIC',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('11','ANTIGUAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('12','ARGENTINE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('13','ARMENIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('14','ARUBIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('15','ASCENSION',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('16','AUSTRALIAN EXTERNAL TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('17','AUSTRALIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('18','AUSTRALIAN ANTARCTIC TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('19','AUSTRIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('20','AZERBAIJANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('21','BAHAMEESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('22','BAHRAINIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('23','BAKER ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('24','BANGLADESHI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('25','BARBADIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('26','BELARUSIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('27','BELGIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('28','BELIZEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('29','BENINESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('30','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('31','BHUTANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('32','BOLIVIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('33','BOSNIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('34','MOTSWANA',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('35','BOUVET ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('36','BRAZILIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('37','BRITISH ANTARCTIC TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('38','BRITISH INDIAN OCEAN TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('39','BRITISH SOVEREIGN BASE AREAS',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('40','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('41','BRUNEIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('42','BULGARIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('43','BURKINABE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('44','MYANMAR',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('45','BURUNDIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('46','CAMBODIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('47','CAMEROONIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('48','CANADIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('49','CAPE VERDEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('50','CARIBBEAN NETHERLANDS',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('51','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('52','CENTRAL AFRICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('53','CHADIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('54','CHILEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('55','CHINESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('56','AUSTRALIAN EXTERNAL TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('57','CLIPPERTON ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('58','AUSTRALIAN EXTERNAL TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('59','COLOMBIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('60','COMORAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('61','CONGOLESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('62','COOK ISLANDER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('63','AUSTRALIAN EXTERNAL TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('64','COSTA RICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('65','IVORIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('66','CROATIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('67','CUBAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('68','CURACAOAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('69','CYPRIOT',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('70','CZECH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('71','CONGOLESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('72','DANISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('73','DJIBOUTIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('74','DOMINICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('75','DOMINICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('76','ECUADOREAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('77','EGYPTIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('78','SALVADOREAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('79','EQUATORIAL GUINEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('80','ERITREAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('81','ESTONIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('82','ETHIOPIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('83','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('84','FAROESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('85','FIJIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('86','FINNISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('87','FRENCH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('88','FRENCH GUIANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('89','FRENCH OVERSEAS COLLECTIVITY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('90','FRENCH SOUTHERN AND ANTARCTIC LANDS',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('91','FRENCH SOUTHERN TERRITORIES',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('92','GABONESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('93','GAMBIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('94','GEORGIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('95','GERMAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('96','GHANAIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('97','GIBRALTARIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('98','GREEK',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('99','GREENLANDER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('100','GRENADIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('101','GUADELOUPEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('102','GUAMANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('103','GUATEMALAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('104','GUERNSEY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('105','GUINEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('106','GUINEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('107','GUYANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('108','HAITIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('109','AUSTRALIAN EXTERNAL TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('110','HONDURAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('111','HONG KONG',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('112','HOWLAND ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('113','HUNGARIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('114','ICELANDER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('115','INDIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('116','INDONESIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('117','IRANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('118','IRAQI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('119','IRISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('120','MANX',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('121','ISRAELI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('122','ITALIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('123','JAMAICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('124','JAPANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('125','JARVIS ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('126','JERSEY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('127','JOHNSTON ATOLL',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('128','JORDANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('129','KAZAKHSTANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('130','KENYAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('131','KINGMAN REEF',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('132','I-KIRIBATI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('133','KOSOVAR',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('134','KUWAITI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('135','KYRGYZSTANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('136','LAOTIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('137','LATVIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('138','LEBANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('139','MOSOTHO',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('140','LIBERIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('141','LIBYAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('142','LIECHTENSTEINER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('143','LITHUNIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('144','LUXEMBOURGER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('145','MACANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('146','MACEDONIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('147','MALAGASY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('148','MALAWIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('149','MALAYSIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('150','MALDIVAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('151','MALIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('152','MALTESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('153','MARSHALLESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('154','MARTINICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('155','MAURITANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('156','MAURITIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('157','MAHORAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('158','MEXICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('159','MICRONESIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('160','U.S. TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('161','MOLDOVAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('162','MONACAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('163','MONGOLIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('164','MONTENEGRIN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('165','MONTSERRATIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('166','MOROCCAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('167','MOZAMBICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('168','NAGORNO-KARABAKH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('169','NAMIBIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('170','NAURUAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('171','NAVASSA ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('172','NEPALESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('173','DUTCH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('174','NEW CALEDONIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('175','NEW ZEALANDER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('176','NICARAGUAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('177','NIGERIEN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('178','NIGERIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('179','NIUEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('180','NORFOLK ISLANDER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('181','NORTH KOREAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('182','U.S. TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('183','U.S. TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('184','NORWEGIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('185','OMANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('186','PAKISTANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('187','PALAUAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('188','PALESTINIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('189','PALMYRA ATOLL',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('190','PANAMANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('191','PAPUA NEW GUINEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('192','PARAGUAYAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('193','PERUVIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('194','PETER I ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('195','FILIPINO',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('196','PITCAIRN ISLANDER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('197','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('198','POLISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('199','PORTUGUESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('200','PRIDNESTROVIE (TRANSNISTRIA)',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('201','PUERTO RICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('202','QATARI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('203','QUEEN MAUD LAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('204','FRENCH OVERSEAS REGION',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('205','ROMANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('206','ROSS DEPENDENCY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('207','RUSSIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('208','RWANDAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('209','FRENCH OVERSEAS COLLECTIVITY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('210','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('211','KITTIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('212','SAINT LUCIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('213','FRENCH OVERSEAS COLLECTIVITY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('214','DUTCH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('215','SAINT-PIERRAIS',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('216','SAINT VINCENTIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('217','SAMOAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('218','SANMARINESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('219','SAO TOMEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('220','SAUDI ARABIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('221','SENEGALESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('222','SERBIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('223','SEYCHELLOIS',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('224','SIERRA LEONEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('225','SINGAPOREAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('226','SLOVAKIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('227','SLOVENIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('228','SOLOMON ISLANDER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('229','SOMALI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('230','SOMALILAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('231','SOUTH AFRICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('232','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('233','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('234','SOUTH KOREAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('235','SOUTH OSSETIA',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('236','SOUTH SUDANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('237','SPANISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('238','SRI LANKAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('239','SUDANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('240','SURINAMER',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('241','SVALBARD AND JAN MAYEN ISLANDS',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('242','SWAZI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('243','SWEDISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('244','SWISS',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('245','SYRIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('246','TAIWANESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('247','TAJIKISTANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('248','TANZANIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('249','THAI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('250','TIMORESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('251','TOGOLESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('252','TOKELAUAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('253','TONGAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('254','TRINIDADIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('255','TRISTAN DA CUNHA',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('256','TUNISIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('257','TURKISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('258','TURKMEN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('259','BRITISH OVERSEAS TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('260','TUVALUAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('261','UGANDAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('262','UKRAINIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('263','EMIRIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('264','BRITISH',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('265','U.S. TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('266','AMERICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('267','U.S. TERRITORY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('268','URUGUAYAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('269','UZBEKISTANI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('270','NI-VANUATU',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('271','VATICAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('272','VENEZUELAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('273','VIETNAMESE',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('274','WAKE ISLAND',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('275','FRENCH OVERSEAS COLLECTIVITY',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('276','WESTERN SAHARAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('277','YEMENI',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('278','ZAMBIAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('279','ZIMBABWEAN',NULL,NULL,NULL,NULL,NULL);
insert into `nationality` (`id`, `name`, `rating`, `is_sanctioned`, `is_active`, `datetime_created`, `datetime_updated`) values('280','UNKNOWN',NULL,NULL,NULL,NULL,NULL);
